### ISSUE TITLE
Seems to open under the current keyboard on ipados-15.8.2

### ISSUE THREAD

**Issue by brian6932** [vyolit/Kayoko#39] opened 2024-04-24 10:17 UTC
**Describe the bug:**

**Steps to reproduce the behavior:**
The prediction bar doesn't work at all for me. The dictation key does, but shows up under the current keyboard.

**System information:**
- iOS version: 15.8.2
- Device: iPad
- Jailbreak: palera1n
- Jailbreak Type: rootful

**Comment by vyolit** [comment] 2024-04-24 11:48
Duplicate of #30.

**Closed by vyolit** 2024-04-24 11:48 UTC
Labels: bug
